apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kafka-test
  description: Kafka Test
  annotations:
    kafka.apache.org/consumer-group: consumer
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: architecture
