apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-scaffolder-test-utils
  title: '@backstage/scaffolder-test-utils'
spec:
  lifecycle: experimental
  type: backstage-node-library
  owner: maintainers
