apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playback-order
  description: Playback Order
  tags:
    - java
    - playback
  annotations:
    splunk-on-call.com/team: Example
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
