apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: artists
  description: Everything related to artists
  links:
    - url: http://example.com/domain/readme
      title: Artists Domain Readme
spec:
  owner: team-a
