app:
  title: Backstage Uffizzi Environment
  baseUrl: ${UFFIZZI_URL}

backend:
  baseUrl: ${UFFIZZI_URL}
  cors:
    origin: ${UFFIZZI_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  auth:
    keys:
      # random mock key for uffizi deployments
      - secret: 5TXvdjVZFxF7qf9K5RAYRDoGrLzJooqa
