# on a PR open on PR review or comment, assign the awaiting-review label if the actor is the author
name: Set Awaiting Review
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  issues: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: fix-labels
        with:
          script: |
            // if it's the author, always add awaiting-review label
            const isAuthor = context.payload.pull_request.user.login === context.actor
            if (isAuthor) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['awaiting-review']
              });
            }
