# New tags and releases are created by changeset https://github.com/atlassian/changesets
name: Create a new release on GitHub when a new tag is created

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v0.4.0, v1.1.0

jobs:
  build:
    name: Create a new release on GitHub when a new tag is created
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release on GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: 'Changelog https://github.com/backstage/backstage/blob/master/CHANGELOG.md'
          draft: false
          prerelease: false
