# on a review from someone in the reviewers group, remove the awaiting-review label and add the awaiting-author label
name: Update labels for awaiting review
on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: get-reviewers
        with:
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          script: |
            const {data: reviewerMembers} = await github.rest.teams.listMembersInOrg({
              org: context.payload.organization.login,
              team_slug: 'reviewers'
            });
            return reviewerMembers;
      - uses: actions/github-script@v5
        id: are-all-reviews-from-reviewers
        with:
          script: |
            const {data: requestedReviewers} = await github.rest.pulls.listRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });


            console.log(requestedReviewers);;     
      - uses: actions/github-script@v5
        id: fix-labels
        with:
          script: |
            const isAuthor = context.payload.pull_request.user.login === context.actor
             if (isAuthor) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['awaiting-review']
              });
