name: Verify Docs Quality
on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/verify_docs-quality.yml'
      - '**.md'

jobs:
  check-all-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Vale does not support file excludes, so we use the script to generate a list of files instead
      - name: list files to check
        id: list
        run: echo "::set-output name=files::$(node scripts/check-docs-quality.js --list)"

      - name: documentation quality check
        uses: errata-ai/vale-action@v1.5.0
        # Whitelist excluding ADOPTERS, CHANGELOG and OWNERS (no exclude flag exists)
        with:
          config: .github/vale/config.ini
          files: '${{ steps.list.files }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
