name: Verify TechDocs MkDocs
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generate the API Reference docs which MkDocs cross-references

      - name: use node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.3
        with:
          cache-prefix: ${{ runner.os }}-v18.x

      - name: build API reference
        run: yarn build:api-docs


      # Setup and start the MkDocs configuration

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip3 install mkdocs mkdocs-techdocs-core

      - name: Build MkDocs for TechDocs
        run: mkdocs build --strict
