name: Verify TechDocs MkDocs
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip3 install mkdocs mkdocs-techdocs-core

      - name: Build MkDocs for TechDocs
        run: mkdocs build --strict
